name: Leave Request
description: Request paid, sick, or unpaid leave
title: "Leave Request: FirstName LastName – YYYY-MM-DD to YYYY-MM-DD"
labels: ["leave-request", "needs-review"]
assignees: ["markholdex"]
body:
  - type: markdown
    attributes:
      value: |
        ## Leave Request Form
        Please fill out all fields below. Submit at least **14 days in advance** (except for sick/emergency leave).
