name: Leave Request
description: Request paid, sick, or unpaid leave
title: "Leave Request: FirstName LastName – YYYY-MM-DD to YYYY-MM-DD"
labels: ["leave-request", "needs-review"]
assignees: ["markholdex"]
body:
  - type: markdown
    attributes:
      value: |
        ## Leave Request Form
        Please fill out all fields below. Submit at least **14 days in advance** (except for sick/emergency leave).

  - type: input
    id: full_name
    attributes:
      label: Full Name
      description: Your full name as in the agreement
      placeholder: John Doe
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: Start Date (inclusive)
      description: First day you will be off (YYYY-MM-DD)
      placeholder: 2025-07-15
    validations:
      required: true

  - type: input
    id: end_date
    attributes:
      label: End Date (inclusive)
      description: Last day you will be off (YYYY-MM-DD)
      placeholder: 2025-07-23
    validations:
      required: true

  - type: input
    id: total_working_days
    attributes:
      label: Total Working Days Requested
      description: Count only Mon–Fri
      placeholder: 7
    validations:
      required: true

  - type: dropdown
    id: leave_type
    attributes:
      label: Leave Type
      options:
        - Paid Leave (Vacation/Personal)
        - Sick Leave
        - Unpaid Leave
        - Emergency Leave
      default: 0
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason (short & clear)
      description: No medical details required for sick leave
      placeholder: Family wedding in Spain • Medical appointment • etc.
    validations:
      required: true

  - type: input
    id: backup_person
    attributes:
      label: Backup / Coverage Person
      description: Who will cover your responsibilities? (@username)
      placeholder: "@jane-doe"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have informed my backup person
          required: true
        - label: I have checked that I have enough paid leave balance (if requesting paid leave)
          required: false

  - type: markdown
    attributes:
      value: |
        Thank you! HR will review within 3 working days.
        You will be notified here when the request is approved or rejected.

