name: Validate Markdown and PR naming

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: holdex/github-actions/.github/actions/base/checkout@main
        with:
          ref: 05eefbf2dfd772dbb2c12b9985d21ac24c5da0e5

      - uses: ./.holdex-actions/.github/actions/base/setup-runtime
        with:
          package-manager: bun

      - uses: ./.holdex-actions/.github/actions/composed/pr-checks
        with:
          run-prettier: false
          run-markdown: true
          run-commits: true
          package-manager: bun
